"""Anchor — a user-supplied (or imported) override for a specific partial parameter.

Anchors live on `Bank.anchors` as an immutable tuple. Adding, patching, or
removing an anchor yields a *new* Bank (with a new id and parent_id pointing
to the previous version) — see `Bank.with_added_anchor` etc.

The six parameter names match the math-layer Literal in
`completion.anchor_interpolate`: tau1 / tau2 / A0 / a1 / beat_hz are direct
Partial fields; `f_coef` is the dimensionless inharmonicity residual used
only in math-layer computations (never stored on Partial).
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Literal

from piano_core.constants import MATH_PARAMS


AnchorOrigin = Literal["manual", "imported", "regression_fit"]

ANCHOR_ORIGINS: tuple[AnchorOrigin, ...] = ("manual", "imported", "regression_fit")


@dataclass(frozen=True, slots=True)
class Anchor:
    """One override point for a note's partial parameter curve.

    Fields
    ------
    id : UUID4 string (auto-generated by default)
    midi, velocity : target note within the bank
    k : partial index (1-based)
    parameter : one of MATH_PARAMS
    value : the override value in the parameter's natural units (Hz for f_coef
        is NOT natural — f_coef is dimensionless by construction; see
        piano_core.splines.bounds.PARAM_BOUNDS)
    weight : stiffness in [0, 1]; 1.0 is a hard anchor (pins the spline)
    origin : provenance tag (user clicked, import from file, regression fit)
    created_at, created_by, note : audit metadata
    """

    midi: int
    velocity: int
    k: int
    parameter: str
    value: float
    weight: float = 0.5
    origin: AnchorOrigin = "manual"
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    created_by: str = "system"
    note: str = ""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))

    def __post_init__(self) -> None:
        if self.parameter not in MATH_PARAMS:
            raise ValueError(
                f"invalid anchor parameter {self.parameter!r}; expected one of {MATH_PARAMS}"
            )
        if not (0.0 <= self.weight <= 1.0):
            raise ValueError(f"anchor weight must lie in [0, 1], got {self.weight}")
        if self.origin not in ANCHOR_ORIGINS:
            raise ValueError(
                f"invalid anchor origin {self.origin!r}; expected one of {ANCHOR_ORIGINS}"
            )
        if self.k < 1:
            raise ValueError(f"anchor k must be >= 1, got {self.k}")

    # ---- serialization -------------------------------------------------

    def as_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "midi": self.midi,
            "velocity": self.velocity,
            "k": self.k,
            "parameter": self.parameter,
            "value": self.value,
            "weight": self.weight,
            "origin": self.origin,
            "created_at": self.created_at.isoformat(),
            "created_by": self.created_by,
            "note": self.note,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Anchor":
        ts_raw = d.get("created_at")
        if isinstance(ts_raw, str):
            ts = datetime.fromisoformat(ts_raw)
        elif isinstance(ts_raw, datetime):
            ts = ts_raw
        else:
            ts = datetime.now(timezone.utc)
        if ts.tzinfo is None:
            ts = ts.replace(tzinfo=timezone.utc)

        return cls(
            id=d.get("id") or str(uuid.uuid4()),
            midi=int(d["midi"]),
            velocity=int(d["velocity"]),
            k=int(d["k"]),
            parameter=str(d["parameter"]),
            value=float(d["value"]),
            weight=float(d.get("weight", 0.5)),
            origin=d.get("origin", "manual"),
            created_at=ts,
            created_by=str(d.get("created_by", "system")),
            note=str(d.get("note", "")),
        )

    # ---- convenience --------------------------------------------------

    def note_key(self) -> tuple[int, int]:
        return (self.midi, self.velocity)

    def patched(
        self,
        *,
        value: float | None = None,
        weight: float | None = None,
        note: str | None = None,
    ) -> "Anchor":
        """Return a new Anchor with the given fields replaced; id stays the same."""
        from dataclasses import replace
        fields_to_change: dict[str, Any] = {}
        if value is not None:
            fields_to_change["value"] = float(value)
        if weight is not None:
            fields_to_change["weight"] = float(weight)
        if note is not None:
            fields_to_change["note"] = note
        return replace(self, **fields_to_change)
